### PR TITLE
added AggregateCreditsResponse interface

### PR DESCRIPTION
**Pull request by odysseaspapadimas**
From [/tv/{tv_id}/aggregate_credits](https://developers.themoviedb.org/3/tv/get-tv-aggregate-credits)

### CODE REVIEW

**Comment by grantholle** [comment]
Yeah it looks like `Cast` needs `roles` (which you've added) and `Crew` jobs. Probably just merge them with the new types you've added.

**Comment by odysseaspapadimas** [comment]
I think we need new types, `Cast` and `Crew` types are still used by the regular [tv/credits/](https://developers.themoviedb.org/3/tv/get-tv-credits) which doesn't return `roles` and `jobs` respectively for cast and crew

> Yeah it looks like `Cast` needs `roles` (which you've added) and `Crew` jobs. Probably just merge them with the new types you've added.

**Comment by grantholle** [comment]
Ok, I guess that's all right then. If you could remove the semicolons and then update the return type for `tvAggregateCredits` to be `Promise<types.AggregateCreditsResponse>`. It should be good to go!

**Comment by odysseaspapadimas** [comment]
I think it's ready now! Thanks

**Comment by grantholle** [comment]
Published v3.2, thanks!

**Pull request merged**
